name: Deploy React Vite App to Pages

on:
  push:
    branches: ["main"] # Triggers the workflow every time you push to main
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  setup-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Create service account file from secret
      shell: bash
      env:
        CREDENTIALS_JSON_CONTENT: ${{ secrets.CREDENTIALS_JSON_CONTENT }}
      run: |
        if [ -z "$CREDENTIALS_JSON_CONTENT" ]; then
          echo "CREDENTIALS_JSON_CONTENT is not set"
          exit 1
        fi
        printf '%s' "$CREDENTIALS_JSON_CONTENT" > credentials.json
  deploy:
    needs: setup-secrets
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Uses a stable Node version
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci # Faster, cleaner install for automated environments

      - name: Build Project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Tells GitHub to grab Vite's compiled output folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    needs:
      - deploy
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.actions.listArtifactsForRepo(context.repo);
            for (const artifact of data.artifacts) {
              await github.rest.actions.deleteArtifact({
                ...context.repo,
                artifact_id: artifact.id
              });
            }